# Generated by Django 5.2.3 on 2025-10-02 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0002_remove_etudiantprofile_slug'),
        ('transactions', '0014_alter_emploiedutemps_nature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.CharField(choices=[('devoir', 'devoir'), ('session', 'session')], default=None, help_text='notes du devoir ou de la session', max_length=50)),
                ('note', models.PositiveSmallIntegerField()),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.matiere_programmer')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.semestre')),
            ],
        ),
    ]
