# Generated by Django 5.2.3 on 2025-08-27 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=255)),
                ('debut_annee', models.DateField()),
                ('fin_annee', models.DateField()),
                ('est_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('heure', models.TimeField()),
                ('montant', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.cycle')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.niveau')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.option')),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frais_inscription', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_reinscription', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_mensuels', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.anneeacademique')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nature', models.CharField(choices=[('inscription', 'Inscription'), ('reinscription', 'Réinscription')], help_text='inscription ou réinscription.', max_length=50)),
                ('ram', models.BooleanField(default=False)),
                ('marqueur', models.BooleanField(default=False)),
                ('dossier_inscription', models.BooleanField(default=False)),
                ('bulletin', models.BooleanField(default=False)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='database.etudiant')),
                ('recu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.recu')),
            ],
            options={
                'unique_together': {('etudiant', 'annee_academique')},
            },
        ),
    ]
