# Generated by Django 5.2.3 on 2025-08-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneeacademique',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
