# Generated by Django 5.2.3 on 2025-09-02 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_etudiantprofile_slug'),
        ('transactions', '0002_anneeacademique_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nom', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PaiementEcolage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.IntegerField()),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.etudiant')),
                ('mois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.mois')),
            ],
        ),
    ]
