# Generated by Django 5.2.3 on 2025-09-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_mois_paiementecolage'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementecolage',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
