# Generated by Django 5.2.3 on 2025-09-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_etudiantprofile_slug'),
        ('transactions', '0004_paiementecolage_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paiementecolage',
            constraint=models.UniqueConstraint(fields=('etudiant', 'annee_academique', 'mois'), name='unique_paiement_par_mois_annee'),
        ),
    ]
