# Generated by Django 5.2.3 on 2025-09-11 11:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_etudiantprofile_slug'),
        ('transactions', '0005_paiementecolage_unique_paiement_par_mois_annee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement_soutenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.etudiant')),
            ],
            options={
                'verbose_name': 'Paiement de soutenance',
                'verbose_name_plural': 'Paiements de soutenance',
                'constraints': [models.UniqueConstraint(fields=('etudiant', 'annee_academique'), name='unique_paiement_soutenance_par_an')],
            },
        ),
    ]
