# Generated by Django 5.2.3 on 2025-09-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_paiement_soutenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement_soutenance',
            name='montant',
            field=models.IntegerField(default=0),
        ),
    ]
