# Generated by Django 5.2.3 on 2025-09-17 12:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_etudiantprofile_slug'),
        ('transactions', '0007_paiement_soutenance_montant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.anneeacademique')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='database.enseignant')),
            ],
            options={
                'unique_together': {('enseignant', 'annee_academique')},
            },
        ),
    ]
