# Generated by Django 5.2.3 on 2025-09-22 11:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_etudiantprofile_slug'),
        ('transactions', '0008_contrat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nom', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('capacite', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matiere_Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.classe')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.CreateModel(
            name='EmploieDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.enseignant')),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.jour')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.matiere_programmer')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6')], max_length=2, verbose_name='Nom du semestre')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description du semestre')),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.anneeacademique')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
            },
        ),
        migrations.AddField(
            model_name='matiere_programmer',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.semestre'),
        ),
    ]
