# Generated by Django 5.2.3 on 2025-09-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_jour_salle_matiere_programmer_emploiedutemps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestre',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='semestre',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='semestre',
            name='mois_debut',
            field=models.CharField(default=None, verbose_name='mois de début'),
        ),
        migrations.AddField(
            model_name='semestre',
            name='mois_fin',
            field=models.CharField(default=None, verbose_name='mois de fin'),
        ),
    ]
