# Generated by Django 5.2.3 on 2025-09-22 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_remove_semestre_date_debut_remove_semestre_date_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploiedutemps',
            name='semestre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transactions.semestre'),
        ),
    ]
