# Generated by Django 5.2.3 on 2025-09-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_emploiedutemps_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploiedutemps',
            name='description',
            field=models.CharField(choices=[('1er', '2er'), ('2eme', '2eme')], default=None, help_text='1er heure ou 2eme heure', max_length=50),
        ),
    ]
