# Generated by Django 5.2.3 on 2025-09-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_emploiedutemps_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emploiedutemps',
            old_name='description',
            new_name='nature',
        ),
    ]
