# Generated by Django 5.2.3 on 2025-09-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_etudiantprofile_slug'),
        ('transactions', '0013_rename_description_emploiedutemps_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploiedutemps',
            name='nature',
            field=models.CharField(choices=[('1er', '1er'), ('2eme', '2eme')], default=None, help_text='1er heure ou 2eme heure', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='emploiedutemps',
            constraint=models.UniqueConstraint(fields=('semestre', 'classe', 'jour', 'nature', 'annee_academique'), name='unique_emploi_du_temps'),
        ),
    ]
