# Generated by Django 5.2.3 on 2025-10-06 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_etudiantprofile_slug'),
        ('transactions', '0014_alter_emploiedutemps_nature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceCours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('date_cours', models.DateField(auto_now=True)),
                ('emploie_id', models.IntegerField(blank=True)),
                ('nombre_heure', models.IntegerField(blank=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.enseignant')),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.jour')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.matiere_programmer')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.salle')),
            ],
            options={
                'unique_together': {('classe', 'annee_academique')},
            },
        ),
    ]
