# Generated by Django 5.2.3 on 2025-10-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_presencecours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presencecours',
            unique_together=set(),
        ),
    ]
