# Generated by Django 5.2.3 on 2025-10-20 10:30

import django.core.validators
import django.db.models.deletion
import transactions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_etudiantprofile_slug'),
        ('transactions', '0016_alter_presencecours_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anneeacademique',
            options={'verbose_name': 'Annee academique', 'verbose_name_plural': 'Annees academique'},
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='contrat',
            options={'verbose_name': 'Contrat', 'verbose_name_plural': 'Contrats '},
        ),
        migrations.AlterModelOptions(
            name='emploiedutemps',
            options={'verbose_name': 'Emploie du temps', 'verbose_name_plural': 'Emploies du temps'},
        ),
        migrations.AlterModelOptions(
            name='jour',
            options={'verbose_name': 'Jour', 'verbose_name_plural': 'Jours'},
        ),
        migrations.AlterModelOptions(
            name='mois',
            options={'verbose_name': 'Mois', 'verbose_name_plural': 'Mois'},
        ),
        migrations.AlterModelOptions(
            name='niveau',
            options={'verbose_name': 'Niveau', 'verbose_name_plural': 'Niveaux'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='paiementecolage',
            options={'verbose_name': "Paiement d'ecolage", 'verbose_name_plural': "Paiement d'ecolages"},
        ),
        migrations.AlterModelOptions(
            name='presencecours',
            options={'verbose_name': 'Presence au cours ', 'verbose_name_plural': 'Presences aux cours'},
        ),
        migrations.AlterModelOptions(
            name='recu',
            options={'verbose_name': 'Recu', 'verbose_name_plural': 'Recus'},
        ),
        migrations.AlterModelOptions(
            name='salle',
            options={'verbose_name': 'Salle', 'verbose_name_plural': 'Salles'},
        ),
        migrations.AlterModelOptions(
            name='tarif',
            options={'verbose_name': 'Tarif ', 'verbose_name_plural': 'Tarifs'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Inscription ou reinscription', 'verbose_name_plural': 'Inscriptions ou reinscriptions'},
        ),
        migrations.CreateModel(
            name='Programmes_Cour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verifier', models.BooleanField(default=False)),
                ('nom', models.CharField(blank=True, max_length=8)),
                ('document', models.FileField(upload_to=transactions.models.upload_to_programmes, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('date_upload', models.DateField(auto_now=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.anneeacademique')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.matiere_programmer')),
            ],
        ),
    ]
