# Generated by Django 5.2.3 on 2025-10-20 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_alter_anneeacademique_options_alter_classe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmes_cour',
            name='classe',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='transactions.classe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programmes_cour',
            name='nom',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
