"""
Django settings for schoolv2 project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os




# Fichier a upload modalite
# DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
# FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
# Options par défaut pour les PDF
PDF_DEFAULT_OPTIONS = {
    "page-size": "A4",
    "margin-top": "15mm",
    "margin-right": "15mm",
    "margin-bottom": "15mm",
    "margin-left": "15mm",
    "encoding": "UTF-8",
    "no-outline": None,
    "quiet": "",
}
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# APPEND_SLASH = False
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-vpv!(@qf)q#_splaumxxb3ag#9sc1ks_m*yzhet7h^pc3n676g"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # Change to False for production

# For production, specify your actual domain
# Example: ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com', 'localhost']
ALLOWED_HOSTS = ['*']  # Only use '*' in development, specify actual domains in production

# Security settings for production
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_REDIRECT_EXEMPT = []


# Application definition

INSTALLED_APPS = [
    "unfold",  # Django Unfold
    "unfold.contrib.filters",  # Optional, to use the dropdown filters
    "unfold.contrib.forms",  # Optional, to use forms
    "unfold.contrib.inlines",  # Optional, to use inlines
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pages",
    "database",
    "utilisateur",
    "transactions",
    "api",
    "notes",
    "pdf",
    # 'utilisateur'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = "schoolv2.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "schoolv2.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

# configuration des media espace de storage des upload

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

LOGIN_URL = "/login/"
# LOGIN_REDIRECT_URL = '/'  # Redirection par défaut (sera écrasée par notre vue custom_login)
AUTH_USER_MODEL = "database.Utilisateur"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "ESCOM Admin",
    "SITE_HEADER": "ESCOM database",
    "SITE_URL": "/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": "light",  # "dark" or "light"
    "COLORS": {
        "primary": {
            "50": "255 248 240",
            "100": "255 231 204",
            "200": "254 205 170",
            "300": "253 174 130",
            "400": "252 129 75",
            "500": "244 67 54",
            "600": "230 30 29",
            "700": "211 47 47",
            "800": "198 40 40",
            "900": "183 28 28",
            "950": "142 20 20",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Applications",
                "separator": True,  # Top border
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "Configuration",
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": "/admin/database/utilisateur/",
                    },
                ],
            },
        ],
    },
    "STYLES": [
        # "/static/css/styles.css",
    ],
    "SCRIPTS": [
        # "/static/js/scripts.js",
    ],
}
